/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/lowpoly_anime_character_cyberstyle.glb --transform 
Files: public/lowpoly_anime_character_cyberstyle.glb [5.44MB] > C:\Users\khvic\Desktop\myenergoplanet\lowpoly_anime_character_cyberstyle-transformed.glb [644.94KB] (88%)
Author: DanlyVostok (https://sketchfab.com/1799danly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-anime-character-cyberstyle-9c284506f1e247348acd0de4151974d6
Title: LowPoly Anime Character CyberStyle
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/lowpoly_anime_character_cyberstyle-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Boots} skeleton={nodes.Object_15.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.BootsToon} skeleton={nodes.Object_16.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Hair} skeleton={nodes.Object_18.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.BootsToon} skeleton={nodes.Object_19.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Implants} skeleton={nodes.Object_21.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.BootsToon} skeleton={nodes.Object_22.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Pants} skeleton={nodes.Object_24.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.BootsToon} skeleton={nodes.Object_25.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Pouch} skeleton={nodes.Object_27.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.BootsToon} skeleton={nodes.Object_28.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Switer} skeleton={nodes.Object_30.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.BootsToon} skeleton={nodes.Object_31.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.VioletBody} skeleton={nodes.Object_33.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.EyeBack} skeleton={nodes.Object_34.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.BootsToon} skeleton={nodes.Object_35.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.Pants} skeleton={nodes.Object_181.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.BootsToon} skeleton={nodes.Object_182.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.Hair} skeleton={nodes.Object_184.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.Pouch} skeleton={nodes.Object_186.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.Implants} skeleton={nodes.Object_188.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
        <skinnedMesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.BootsToon} skeleton={nodes.Object_189.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.898} />
      </group>
    </group>
  )
}

useGLTF.preload('/lowpoly_anime_character_cyberstyle-transformed.glb')
