/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gameassets/buildings/rts_human_house_lv2_-_proto_series.glb --transform 
Files: public/gameassets/buildings/rts_human_house_lv2_-_proto_series.glb [974.28KB] > C:\Users\khvic\Desktop\myenergoplanet\rts_human_house_lv2_-_proto_series-transformed.glb [107.74KB] (89%)
Author: BitGem (https://sketchfab.com/bitgem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rts-human-house-lv2-proto-series-d186eaa8f042412db5964fe4a3e91a96
Title: RTS Human House Lv2 - Proto Series
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/rts_human_house_lv2_-_proto_series-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="house_Lv2_door" position={[43.239, 249.975, 257.245]}>
            <group name="house_Lv2_door_handler" position={[-76.282, -4.416, 5.378]} rotation={[-1.573, 0, 0]}>
              <mesh name="house_Lv2_door_handler_proto_human_rts_0" geometry={nodes.house_Lv2_door_handler_proto_human_rts_0.geometry} material={materials.proto_human_rts} />
            </group>
            <mesh name="house_Lv2_door_proto_human_rts_0" geometry={nodes.house_Lv2_door_proto_human_rts_0.geometry} material={materials.proto_human_rts} />
          </group>
        </group>
        <mesh name="house_Lv2_proto_human_rts_0" geometry={nodes.house_Lv2_proto_human_rts_0.geometry} material={materials.proto_human_rts} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/rts_human_house_lv2_-_proto_series-transformed.glb')
