import { defaultCache } from "@serwist/next/worker";
import type { PrecacheEntry, SerwistGlobalConfig } from "serwist";
import { Serwist } from "serwist";

// Extend ServiceWorkerGlobalScope with the Serwist config type
declare global {
  interface ServiceWorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}

declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  // Precache the manifest entries generated by @serwist/next at build time
  precacheEntries: self.__SW_MANIFEST,
  // Take over immediately on install — no waiting for old SW to die
  skipWaiting: true,
  clientsClaim: true,
  // Use Navigation Preload to speed up document requests while SW boots
  navigationPreload: true,
  // Use the default stale-while-revalidate / cache-first strategies
  runtimeCaching: defaultCache,
});

serwist.addEventListeners();
